version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      minor:
        update-types:
          - minor
      patches:
        update-types:
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: tuesday
    groups:
      minor:
        update-types:
          - minor
      patches:
        update-types:
          - patch
