version: 2

updates:
  - package-ecosystem: gomod
    directory: /sample-go-app
    schedule:
      interval: weekly
    groups:
      minor:
        update-types:
          - minor
      patches:
        update-types:
          - patch

  - package-ecosystem: gomod
    directory: /sample-go-app/tools
    schedule:
      interval: weekly
    groups:
      minor:
        update-types:
          - minor
      patches:
        update-types:
          - patch

  - package-ecosystem: pip
    directory: /sample-py-app
    schedule:
      interval: weekly
    groups:
      minor:
        update-types:
          - minor
      patches:
        update-types:
          - patch

  - package-ecosystem: docker
    directory: /sample-go-app
    schedule:
      interval: weekly
    groups:
      minor:
        update-types:
          - minor
      patches:
        update-types:
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      minor:
        update-types:
          - minor
      patches:
        update-types:
          - patch
