/**
 * Kerberos administration API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DebugSession { 
    /**
     * The ID for the debug session.
     */
    id: number;
    /**
     * The backend that the call was made to.
     */
    backend: string;
    /**
     * The time when the debug session started.
     */
    startedAt: string;
    /**
     * The time when the debug session expires.
     */
    expiresAt: string;
    /**
     * The time when the debug session was stopped. Null if the session is still active.
     */
    stoppedAt?: string;
}

