/**
 * Kerberos administration API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FlowTransition } from './flow-transition';


export interface DebugSessionCall { 
    /**
     * The ID for the call.
     */
    id: number;
    /**
     * The time when the call was received.
     */
    startedAt: string;
    /**
     * The time when the call was finished being handled. Null if the call is still being handled.
     */
    stoppedAt: string;
    /**
     * The full URL of the request.
     */
    url: string;
    /**
     * The HTTP method of the operation.
     */
    method: string;
    /**
     * The HTTP status code of the response.
     */
    statusCode: number;
    /**
     * The flow transitions that occurred during this operation, in chronological order.
     */
    flowTransitions: Array<FlowTransition>;
}

