/**
 * Kerberos administration API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ExtendDebugSessionRequest { 
    /**
     * Additional duration in seconds to keep the backend in debug mode. Total duration cannot exceed 1 hour.
     */
    additionalDurationSeconds: number;
}

