/**
 * Kerberos administration API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FlowMetaDataObservability } from './flow-meta-data-observability';
import { FlowMetaDataAuthMethods } from './flow-meta-data-auth-methods';
import { FlowMetaDataAuthScheme } from './flow-meta-data-auth-scheme';
import { FlowMetaDataRouter } from './flow-meta-data-router';
import { FlowMetaDataAuth } from './flow-meta-data-auth';
import { FlowMetaDataOAS } from './flow-meta-data-oas';


/**
 * The metadata for the flow component. The structure of the metadata depends on the flow component.
 */
export interface FlowMetaData { 
    enabled: boolean;
    backends?: Array<string>;
    methods?: FlowMetaDataAuthMethods;
    scheme?: FlowMetaDataAuthScheme;
}

