/**
 * Kerberos administration API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FlowMetaDataAuthMethods } from './flow-meta-data-auth-methods';
import { FlowMetaDataAuthScheme } from './flow-meta-data-auth-scheme';


export interface FlowMetaDataAuth { 
    methods?: FlowMetaDataAuthMethods;
    scheme?: FlowMetaDataAuthScheme;
}

