/**
 * Kerberos administration API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FlowTransitionResult } from './flow-transition-result';


/**
 * A flow transition that occurred during a debug session call. A flow transition represents  a flow component\'s handling of a request, in both directions. 
 */
export interface FlowTransition { 
    /**
     * The flow component that the transition corresponds to.
     */
    component: string;
    /**
     * The direction of the flow transition. Some components handle requests both coming into the system (inbound) and going out of the system (outbound). 
     */
    direction: FlowTransition.DirectionEnum;
    /**
     * The time when the flow transition started.
     */
    startedAt: string;
    /**
     * The time when the flow transition stopped. Null if the transition is still active.
     */
    stoppedAt: string;
    result: FlowTransitionResult;
}
export namespace FlowTransition {
    export const DirectionEnum = {
        Inbound: 'inbound',
        Outbound: 'outbound'
    } as const;
    export type DirectionEnum = typeof DirectionEnum[keyof typeof DirectionEnum];
}


