/**
 * Kerberos administration API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FlowMetaDataAuthSchemeMapping } from './flow-meta-data-auth-scheme-mapping';


export interface FlowMetaDataAuthScheme { 
    mappings?: Array<FlowMetaDataAuthSchemeMapping>;
}

