/**
 * Kerberos administration API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FlowMetaDataAuthSchemeMappingAuthorization } from './flow-meta-data-auth-scheme-mapping-authorization';


export interface FlowMetaDataAuthSchemeMapping { 
    backend: string;
    method: string;
    exempt?: Array<string>;
    authorization?: FlowMetaDataAuthSchemeMappingAuthorization;
}

