/**
 * Kerberos administration API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Permission } from './permission';


export interface Group { 
    id: number;
    name: string;
    /**
     * The permissions that the group has. This may or may not be set depending on the endpoint. 
     */
    permissions?: Array<Permission>;
}

