/**
 * Kerberos administration API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { APIErrorResponse } from '../model/models';
import { ChangeUserPasswordRequest } from '../model/models';
import { CreateGroupRequest } from '../model/models';
import { CreateUserRequest } from '../model/models';
import { DebugSession } from '../model/models';
import { DebugSessionCall } from '../model/models';
import { ExtendDebugSessionRequest } from '../model/models';
import { FlowMeta } from '../model/models';
import { Group } from '../model/models';
import { LoginSuperuserRequest } from '../model/models';
import { Permission } from '../model/models';
import { StartDebugSessionRequest } from '../model/models';
import { UpdateUserGroupsRequest } from '../model/models';
import { UpdateUserRequest } from '../model/models';
import { User } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface DefaultServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param userID 
     * @param changeUserPasswordRequest Request body for changing a user\&#39;s password.
     */
    changeUserPassword(userID: number, changeUserPasswordRequest: ChangeUserPasswordRequest, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param createGroupRequest Request body for creating a group.
     */
    createGroup(createGroupRequest: CreateGroupRequest, extraHttpRequestParams?: any): Observable<Group>;

    /**
     * 
     * 
     * @param createUserRequest Request body for creating a user.
     */
    createUser(createUserRequest: CreateUserRequest, extraHttpRequestParams?: any): Observable<User>;

    /**
     * 
     * 
     * @param backend 
     * @param sessionId 
     */
    deleteDebugSession(backend: string, sessionId: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param groupID 
     */
    deleteGroup(groupID: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param userID 
     */
    deleteUser(userID: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param backend 
     * @param sessionId 
     * @param extendDebugSessionRequest 
     */
    extendDebugSession(backend: string, sessionId: number, extendDebugSessionRequest: ExtendDebugSessionRequest, extraHttpRequestParams?: any): Observable<DebugSession>;

    /**
     * 
     * 
     * @param backend 
     */
    getBackendOAS(backend: string, extraHttpRequestParams?: any): Observable<{ [key: string]: any; }>;

    /**
     * 
     * 
     * @param backend 
     * @param sessionId 
     */
    getDebugSession(backend: string, sessionId: number, extraHttpRequestParams?: any): Observable<DebugSession>;

    /**
     * 
     * 
     * @param backend 
     * @param sessionId 
     * @param callId 
     */
    getDebugSessionCall(backend: string, sessionId: number, callId: number, extraHttpRequestParams?: any): Observable<DebugSessionCall>;

    /**
     * 
     * 
     */
    getFlow(extraHttpRequestParams?: any): Observable<Array<FlowMeta>>;

    /**
     * 
     * 
     * @param groupID 
     */
    getGroup(groupID: number, extraHttpRequestParams?: any): Observable<Group>;

    /**
     * 
     * 
     */
    getGroups(extraHttpRequestParams?: any): Observable<Array<Group>>;

    /**
     * 
     * 
     */
    getPermissions(extraHttpRequestParams?: any): Observable<Array<Permission>>;

    /**
     * 
     * 
     * @param userID 
     */
    getUser(userID: number, extraHttpRequestParams?: any): Observable<User>;

    /**
     * 
     * 
     */
    getUsers(extraHttpRequestParams?: any): Observable<Array<User>>;

    /**
     * 
     * 
     * @param backend 
     * @param sessionId 
     * @param includeTransitions 
     */
    listDebugSessionCalls(backend: string, sessionId: number, includeTransitions: boolean, extraHttpRequestParams?: any): Observable<Array<DebugSessionCall>>;

    /**
     * 
     * 
     * @param backend 
     */
    listDebugSessions(backend: string, extraHttpRequestParams?: any): Observable<Array<DebugSession>>;

    /**
     * 
     * 
     * @param createUserRequest Request body for logging a user in.
     */
    login(createUserRequest: CreateUserRequest, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param loginSuperuserRequest 
     */
    loginSuperuser(loginSuperuserRequest: LoginSuperuserRequest, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    logout(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    logoutSuperuser(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param backend 
     * @param startDebugSessionRequest Request body for starting a debug session for a backend.
     */
    startDebugSession(backend: string, startDebugSessionRequest?: StartDebugSessionRequest, extraHttpRequestParams?: any): Observable<DebugSession>;

    /**
     * 
     * 
     * @param backend 
     * @param sessionId 
     */
    stopDebugSession(backend: string, sessionId: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param groupID 
     * @param createGroupRequest Request body for updating a group.
     */
    updateGroup(groupID: number, createGroupRequest: CreateGroupRequest, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param userID 
     * @param updateUserRequest Request body for updating a user.
     */
    updateUser(userID: number, updateUserRequest: UpdateUserRequest, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param userID 
     * @param updateUserGroupsRequest Request body for updating a user\&#39;s groups.
     */
    updateUserGroups(userID: number, updateUserGroupsRequest: UpdateUserGroupsRequest, extraHttpRequestParams?: any): Observable<{}>;

}
