/**
 * Kerberos basic authentication API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { APIErrorResponse } from '../model/models';
import { ChangePasswordRequest } from '../model/models';
import { CreateGroupRequest } from '../model/models';
import { CreateOrganisation201Response } from '../model/models';
import { CreateOrganisationRequest } from '../model/models';
import { CreateUserRequest } from '../model/models';
import { Group } from '../model/models';
import { LoginRequest } from '../model/models';
import { Organisation } from '../model/models';
import { User } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface DefaultServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param orgID An organisation ID.
     * @param userID A user ID.
     * @param changePasswordRequest 
     */
    changePassword(orgID: number, userID: number, changePasswordRequest: ChangePasswordRequest, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param orgID An organisation ID.
     * @param createGroupRequest 
     */
    createGroup(orgID: number, createGroupRequest: CreateGroupRequest, extraHttpRequestParams?: any): Observable<Group>;

    /**
     * 
     * 
     * @param createOrganisationRequest 
     */
    createOrganisation(createOrganisationRequest: CreateOrganisationRequest, extraHttpRequestParams?: any): Observable<CreateOrganisation201Response>;

    /**
     * 
     * 
     * @param orgID An organisation ID.
     * @param createUserRequest 
     */
    createUser(orgID: number, createUserRequest: CreateUserRequest, extraHttpRequestParams?: any): Observable<User>;

    /**
     * 
     * 
     * @param orgID An organisation ID.
     * @param groupID A group ID.
     */
    deleteGroup(orgID: number, groupID: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param orgID An organisation ID.
     */
    deleteOrganisation(orgID: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param orgID An organisation ID.
     * @param userID A user ID.
     */
    deleteUser(orgID: number, userID: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param orgID An organisation ID.
     * @param groupID A group ID.
     */
    getGroup(orgID: number, groupID: number, extraHttpRequestParams?: any): Observable<Group>;

    /**
     * 
     * 
     * @param orgID An organisation ID.
     */
    getOrganisation(orgID: number, extraHttpRequestParams?: any): Observable<Organisation>;

    /**
     * 
     * 
     * @param orgID An organisation ID.
     * @param userID A user ID.
     */
    getUser(orgID: number, userID: number, extraHttpRequestParams?: any): Observable<User>;

    /**
     * 
     * 
     * @param orgID An organisation ID.
     * @param userID A user ID.
     */
    getUserGroups(orgID: number, userID: number, extraHttpRequestParams?: any): Observable<Array<string>>;

    /**
     * 
     * 
     * @param orgID An organisation ID.
     */
    listGroups(orgID: number, extraHttpRequestParams?: any): Observable<Array<Group>>;

    /**
     * 
     * 
     */
    listOrganisations(extraHttpRequestParams?: any): Observable<Array<Organisation>>;

    /**
     * 
     * 
     * @param orgID An organisation ID.
     */
    listUsers(orgID: number, extraHttpRequestParams?: any): Observable<Array<User>>;

    /**
     * 
     * 
     * @param orgID An organisation ID.
     * @param loginRequest 
     */
    login(orgID: number, loginRequest: LoginRequest, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param orgID An organisation ID.
     */
    logout(orgID: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param orgID An organisation ID.
     * @param groupID A group ID.
     * @param group 
     */
    updateGroup(orgID: number, groupID: number, group: Group, extraHttpRequestParams?: any): Observable<Group>;

    /**
     * 
     * 
     * @param orgID An organisation ID.
     * @param organisation 
     */
    updateOrganisation(orgID: number, organisation: Organisation, extraHttpRequestParams?: any): Observable<Organisation>;

    /**
     * 
     * 
     * @param orgID An organisation ID.
     * @param userID A user ID.
     * @param user 
     */
    updateUser(orgID: number, userID: number, user: User, extraHttpRequestParams?: any): Observable<User>;

    /**
     * 
     * 
     * @param orgID An organisation ID.
     * @param userID A user ID.
     * @param requestBody 
     */
    updateUserGroups(orgID: number, userID: number, requestBody: Array<string>, extraHttpRequestParams?: any): Observable<Array<string>>;

}
