/**
 * Kerberos basic authentication API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateOrganisation201Response { 
    id: number;
    name: string;
    adminUserId: number;
    adminUsername: string;
    adminPassword: string;
}

