name: Main branch protection

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  static-analysis:
    uses: ./.github/workflows/callable-static-analysis.yaml

  build:
    uses: ./.github/workflows/callable-build.yaml

  test:
    uses: ./.github/workflows/callable-test.yaml
